// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEGbrXoN-zTIyzKXKzIM0bZpr8TOvWMRA',
    appId: '1:976067132635:web:288b21beb890746b6d60fe',
    messagingSenderId: '976067132635',
    projectId: 'examendenicolas0303',
    authDomain: 'examendenicolas0303.firebaseapp.com',
    storageBucket: 'examendenicolas0303.appspot.com',
    measurementId: 'G-GP2XB7TRNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVat8T3VmhDeCV0Dr0s2W0mO74i7loN0',
    appId: '1:976067132635:android:e44ec746cd9d63fa6d60fe',
    messagingSenderId: '976067132635',
    projectId: 'examendenicolas0303',
    storageBucket: 'examendenicolas0303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLlfjAtjowHmzrelEvBcS-nfxEwoxULpg',
    appId: '1:976067132635:ios:e148cd91b3856a046d60fe',
    messagingSenderId: '976067132635',
    projectId: 'examendenicolas0303',
    storageBucket: 'examendenicolas0303.appspot.com',
    iosBundleId: 'com.example.examenNicolascontreras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLlfjAtjowHmzrelEvBcS-nfxEwoxULpg',
    appId: '1:976067132635:ios:e148cd91b3856a046d60fe',
    messagingSenderId: '976067132635',
    projectId: 'examendenicolas0303',
    storageBucket: 'examendenicolas0303.appspot.com',
    iosBundleId: 'com.example.examenNicolascontreras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEGbrXoN-zTIyzKXKzIM0bZpr8TOvWMRA',
    appId: '1:976067132635:web:1b69c9f85ebed7026d60fe',
    messagingSenderId: '976067132635',
    projectId: 'examendenicolas0303',
    authDomain: 'examendenicolas0303.firebaseapp.com',
    storageBucket: 'examendenicolas0303.appspot.com',
    measurementId: 'G-Q1LFG9ZHRG',
  );
}
